export const serviceData = [
  {
    id: 1,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 2,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 3,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 4,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 5,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 6,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 7,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 8,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 9,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 10,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 11,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 12,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 13,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 14,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 15,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 16,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 17,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 18,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 19,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 20,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
  {
    id: 21,
    title: "Web Development Project",
    category: "Web Development",
    subCategory: ["Frontend", "Backend"],
    skills: ["React", "Node.js", "CSS"],
    price: "1000",
    priorityLevel: "High",
    projectDescription:
      "A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.A comprehensive web development project.",
    createdAt: new Date("2023-01-01"),
    expectedStartDate: new Date("2023-02-01"),
    expectedEndDate: new Date("2023-03-01"),
  },
];

export const projectData = [
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
  {
    category: "Web Development",
    subCategory: "Frontend",
    skill: [
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
      "React",
      "TypeScript",
      "CSS",
      "HTML",
      "JavaScript",
    ],
  },
];
